// Generated by tools/assets/build_escape_furniture.py — do not edit by hand.
// A 3D box for every painted object the clip mask knows about that has no real
// model standing on it. See the generator for the reasoning and the region colours.
import simd

enum SchoolEscapeFurniture {
    /// (centre x, centre y, width, length, height, colour) in map pixels.
    static let boxes: [(x: Double, y: Double, w: Float, l: Float, h: Float, hex: String)] = [
        (-2455, -1300, 200, 90, 190, "#5d3f24"),
        (-1800, -1300, 200, 90, 190, "#5d3f24"),
        (2600, -725, 200, 650, 140, "#8f979c"),
        (-250, -700, 64, 72, 55, "#d8d8d8"),
        (75, -700, 64, 72, 55, "#d8d8d8"),
        (1930, -665, 120, 550, 140, "#8f979c"),
        (2262, -660, 208, 320, 140, "#8f979c"),
        (-95, -655, 64, 48, 75, "#d8d8d8"),
        (215, -655, 64, 48, 75, "#d8d8d8"),
        (-1540, -520, 64, 288, 115, "#6b4a2a"),
        (-1526, -106, 96, 256, 70, "#71512f"),
        (-780, -40, 380, 80, 105, "#6b4a2a"),
        (-940, 30, 80, 160, 105, "#6b4a2a"),
        (-350, 594, 32, 64, 115, "#6b4a2a"),
        (1966, 656, 64, 80, 115, "#6b4a2a"),
        (-2236, 1242, 112, 80, 115, "#6b4a2a"),
        (-2068, 1242, 112, 80, 115, "#6b4a2a"),
        (-2410, 1246, 112, 80, 115, "#6b4a2a"),
        (-2068, 1302, 64, 48, 115, "#6b4a2a"),
        (-2410, 1304, 64, 48, 115, "#6b4a2a"),
        (-2236, 1304, 64, 48, 115, "#6b4a2a"),
    ]

    static let primitives: [ScenePrimitive] = boxes.map { box in
        ScenePrimitive(shape: .box(width: box.w, height: box.l, depth: box.h),
                       transform: Float4x4.translation(SIMD3(Float(box.x),
                                                             Float(-box.y),
                                                             box.h / 2)),
                       color: parseHexColor(box.hex),
                       roughness: 0.85)
    }
}
